transactions = [
    {
        "id": 1,
        "type": "income",
        "amount": 2000.00,
        "date": "2025-05-08",
        "description": "Salary for May",
        "category": "Salary",
        "account": "Bank",
    },
    {
        "id": 2,
        "type": "income",
        "amount": 200.00,
        "date": "2025-05-10",
        "description": "Travel Allowance",
        "category": "Allowance",
        "account": "Cash",
    },
    {
        "id": 3,
        "type": "expense",
        "amount": 50.00,
        "date": "2025-05-12",
        "description": "Lunch with friends",
        "category": "Food",
        "account": "Cash",
    },
    {
        "id": 4,
        "type": "expense",
        "amount": 100.00,
        "date": "2025-05-15",
        "description": "Groceries",
        "category": "Food",
        "account": "Bank",
    },
    {
        "id": 5,
        "type": "income",
        "amount": 300.00,
        "date": "2025-05-20",
        "description": "Freelance Project Payment",
        "category": "Freelance",
        "account": "TNG",
    },
]